name: Development

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - uses: actions/checkout@v4.1.1

            - name: Setup Node.js environment
              uses: actions/setup-node@v4.0.2

            - name: Install npm dependencies
              run: npm install

            - name: Run build task
              run: npm run build --if-present
              env:
                  REACT_APP_FIREBASE_API_KEY: ${{ secrets.DEV_FIREBASE_API_KEY }}
                  REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.DEV_FIREBASE_MESSAGING_SENDER_ID }}
                  REACT_APP_FIREBASE_APP_ID: ${{ secrets.DEV_FIREBASE_APP_ID }}
                  REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.DEV_FIREBASE_AUTH_DOMAIN }}
                  REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.DEV_FIREBASE_PROJECT_ID }}
                  REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.DEV_FIREBASE_STORAGE_BUCKET }}

            - name: Add commit hash to index.html
              run: 'echo "<!--Commit Hash: $(git rev-parse HEAD)-->" >> build/index.html'

            - name: ssh deploy
              uses: easingthemes/ssh-deploy@v5.0.2
              with:
                  # Private Key
                  SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
                  # Remote host
                  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
                  # Remote user
                  REMOTE_USER: ${{ secrets.REMOTE_USER }}
                  SOURCE: 'build/'
                  # Target directory
                  TARGET: ${{ secrets.DEV_REMOTE_TARGET }}
